name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@09c4593
  
    - name: Nuget Restore 
      run:  nuget restore .\WpfAppMain.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
      
 #   - name: Build Unit Tests with msbuild
 #     run: msbuild UnitTestProject1\UnitTestProject1.csproj 
 #   - name: Build App with msbuild 2
 #     run: msbuild WpfApp1\WpfApp1.csproj 
    - name: Build with script
      run: .\Scripts\build.ps1
    - name: Test app
      run: vstest.console.exe /Platform:x64 .\UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll
       
    - name: Sign app
      uses: DanaBear/code-sign-action@bac9e76c5f8ce95462b2981999930bc80756982a
      with:
        certificate: '${{ secrets.CERTNOPASS }}'
        certificatename: '${{ secrets.CERTNAME }}'
        folder: 'WpfApp1/bin/Debug'
        recursive: true

    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: WpfApp1/bin/Debug
    
    - name: AWS
      uses: chrislennon/action-aws-cli@v1.1
        # All commands after this point have access to the AWS CLI
    - run: aws s3 cp ./WpfApp1/bin/Debug/WpfApp1.exe s3://danatestingbucket --region us-east-2
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          


